### ISSUE TITLE
question about usg config

### ISSUE THREAD

**Issue by ggilley** [nicolerenee/k8s-state#2]
I noticed that you were exposing your public ip addresses through metallb. I'm setting up bgp for my usg for metallb as well. I'm curious how you did that on the USG side. Would you mind sharing your config.gateway.json file? My email address is ggilley@gerg.org if that's a better way to share it. Thanks!

**Comment by nicolerenee** [comment]
I'm sorry I missed this issue until just now. Included in the repo is the
`config.gateway.json` that I use on my UniFi server to configure BGP and a few
other things. To learn more about how you can set this up check out these
[docs](https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-How-to-further-customize-USG-configuration-with-config-gateway-json). Hope this helps.
